# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cuporServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=612)),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'acupor_servicios',
                'verbose_name': 'Servicio troncal',
                'verbose_name_plural': 'Servicios Troncales',
            },
        ),
        migrations.CreateModel(
            name='Pak_cupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField(blank=True, null=True, verbose_name=b'Fecha Hab')),
                ('periodo', models.CharField(choices=[('SMNL', 'Semanal'), ('QNCNL', 'Quincenal'), ('MNSL', 'Mensual'), ('OTROS', 'OTROS')], default=b'SMNL', max_length=12, verbose_name=b'PERIODO')),
                ('ncupo', models.IntegerField(default=2, verbose_name=b'Cupo')),
                ('comentarios', models.TextField(default=b'Comentarios')),
            ],
            options={
                'ordering': ['inst', 'depak'],
                'db_table': 'acupor_pakscupos',
                'verbose_name': 'Cupo definido',
                'verbose_name_plural': 'Cupos Determinados',
            },
        ),
        migrations.CreateModel(
            name='Pak_of_inst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name=b'Validez')),
                ('sistema', models.CharField(choices=[('DTTECH', 'Datatech'), ('SISR', 'Sist-APS'), ('OTROS', 'Otros')], default=b'DTTECH', max_length=6, verbose_name=b'SIST AGENDA')),
                ('fecha_ini', models.DateField(blank=True, null=True, verbose_name=b'Fecha Cons')),
                ('periodo', models.CharField(choices=[('SMNL', 'Semanal'), ('QNCNL', 'Quincenal'), ('MNSL', 'Mensual')], default=b'SMNL', max_length=12, verbose_name=b'Periodo')),
                ('turnos', models.IntegerField(default=100, verbose_name=b'Turnos Tots')),
                ('acupturnos', models.IntegerField(default=80, verbose_name=b'Dispo x CUP')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name=b'Fin de Validez')),
                ('comentarios', models.CharField(default=b'Comentarios', max_length=369, verbose_name=b'Comentarios')),
            ],
            options={
                'ordering': ['institucion', 'srvcupor'],
                'db_table': 'acupor_ofertas_inst',
                'verbose_name': 'Paquete InstSrvEsp',
                'verbose_name_plural': 'Pktes X INST',
            },
        ),
        migrations.CreateModel(
            name='PkSrvEsp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=12)),
                ('descripcion', models.CharField(default=b'Descripcion', max_length=524)),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'acupor_especs',
                'verbose_name': 'SRV/Sub',
                'verbose_name_plural': 'SubServicios',
            },
        ),
    ]
