# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('entornos', '0003_obrasocial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuporEspecialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=12)),
                ('descripcion', models.CharField(default=b'Descripcion', max_length=524)),
                ('areadep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name=b'Area de Dependencia')),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'acupor_especs',
                'verbose_name': 'SRV/Sub',
                'verbose_name_plural': 'SubServicios',
            },
        ),
        migrations.CreateModel(
            name='cuporServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=612)),
            ],
            options={
                'ordering': ['codigo'],
                'db_table': 'acupor_servicios',
                'verbose_name': 'Servicio troncal',
                'verbose_name_plural': 'Servicios Troncales',
            },
        ),
        migrations.CreateModel(
            name='Pak_cupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField(blank=True, null=True, verbose_name=b'Fecha Hab')),
                ('sistema', models.CharField(choices=[('DTTECH', 'Datatech'), ('SISR', 'Sist-APS'), ('OTROS', 'Otros')], default=b'SISR', max_length=12, verbose_name=b'Sist Agenda')),
                ('ncupo', models.IntegerField(default=2, verbose_name=b'Cupo')),
                ('comentarios', models.TextField(default=b'Comentarios')),
            ],
            options={
                'ordering': ['inst', 'depak'],
                'db_table': 'acupor_pakscupos',
                'verbose_name': 'Cupo definido',
                'verbose_name_plural': 'Cupos Determinados',
            },
        ),
        migrations.CreateModel(
            name='Pak_of',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField(blank=True, null=True, verbose_name=b'Fecha Cons')),
                ('periodo', models.CharField(choices=[('SMNL', 'Semanal'), ('QNCNL', 'Quincenal'), ('MNSL', 'Mensual')], default=b'SMNL', max_length=12, verbose_name=b'Periodo')),
                ('toturnos', models.IntegerField(default=100, verbose_name=b'Turnos Tots')),
                ('acupturnos', models.IntegerField(default=80, verbose_name=b'Dispo x CUP')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name=b'Fin de Validez')),
                ('comentarios', models.CharField(default=b'Comentarios', max_length=369, verbose_name=b'Comentarios')),
                ('asglabs', models.ManyToManyField(to='servicios.Asigna_lab', verbose_name=b'Modulos Asignados')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'INST RFRNTE')),
                ('srvcupor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acupor.cuporEspecialidad', verbose_name=b'SRV-ESP')),
            ],
            options={
                'ordering': ['institucion', 'srvcupor'],
                'db_table': 'acupor_ofertas',
                'verbose_name': 'Paquete InstSrvEsp',
                'verbose_name_plural': 'Pktes Cuporizables',
            },
        ),
        migrations.AddField(
            model_name='pak_cupo',
            name='depak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acupor.Pak_of', verbose_name=b'Origen'),
        ),
        migrations.AddField(
            model_name='pak_cupo',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'Cupo Para '),
        ),
        migrations.AddField(
            model_name='cuporespecialidad',
            name='dqserv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acupor.cuporServicio', verbose_name=b'Servicio Referente'),
        ),
    ]
