# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0001_initial'),
        ('acupor', '0001_initial'),
        ('entornos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pksrvesp',
            name='areadep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name=b'Area de Dependencia'),
        ),
        migrations.AddField(
            model_name='pksrvesp',
            name='dqserv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acupor.cuporServicio', verbose_name=b'Servicio Referente'),
        ),
        migrations.AddField(
            model_name='pak_of_inst',
            name='asglabs',
            field=models.ManyToManyField(to='servicios.Asigna_lab', verbose_name=b'Modulos Asignados'),
        ),
        migrations.AddField(
            model_name='pak_of_inst',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'INST RFRNTE'),
        ),
        migrations.AddField(
            model_name='pak_of_inst',
            name='srvcupor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acupor.PkSrvEsp', verbose_name=b'PKSRVESP'),
        ),
        migrations.AddField(
            model_name='pak_cupo',
            name='depak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acupor.Pak_of_inst', verbose_name=b'Origen Turnos'),
        ),
        migrations.AddField(
            model_name='pak_cupo',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'Institucion'),
        ),
    ]
