# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acupor', '0002_auto_20180514_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuporservicio',
            options={'ordering': ['codigo'], 'verbose_name': 'SERVICIO TRONCAL', 'verbose_name_plural': 'Servicios Troncales'},
        ),
        migrations.AlterModelOptions(
            name='pak_of_inst',
            options={'ordering': ['institucion', 'srvcupor'], 'verbose_name': 'TURNOS OFRECIDOS', 'verbose_name_plural': 'OFERTAS DE TURNOS'},
        ),
        migrations.AlterModelOptions(
            name='pksrvesp',
            options={'ordering': ['codigo'], 'verbose_name': 'ESP SERVICIO', 'verbose_name_plural': 'SERVICIOS OFRECIDOS'},
        ),
        migrations.AddField(
            model_name='pak_cupo',
            name='vistoxdcs',
            field=models.NullBooleanField(default=False, verbose_name=b'Visto X DCS'),
        ),
        migrations.AlterField(
            model_name='pak_cupo',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'INST ADJUDICADA'),
        ),
        migrations.AlterField(
            model_name='pak_cupo',
            name='ncupo',
            field=models.IntegerField(default=2, verbose_name=b'Turnos destinados'),
        ),
        migrations.AlterField(
            model_name='pak_of_inst',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'INST OFERENTE'),
        ),
    ]
