# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-26 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia_trb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generavacgen', models.BooleanField(default=False, verbose_name=b'Vac Genuina')),
                ('solicita_cobertura', models.BooleanField(default=False, verbose_name=b'X Cubrir')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name=b'Ini Ausencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name=b'Fecha Fin Ausencia')),
                ('fecha_insert', models.DateField(auto_now=True)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name=b'Comentarios')),
            ],
            options={
                'db_table': 'ausencias_trbs',
                'verbose_name': 'Ausencia TRB',
                'verbose_name_plural': 'Ausencias de Personal',
            },
        ),
        migrations.CreateModel(
            name='Dispo_Gestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposicion', models.CharField(choices=[('COMISION', ''), ('CBIOFUNC', ''), ('LSGSDO', 'Lic Sin Goce de Sueldo'), ('RO', 'Re')], max_length=16, verbose_name=b'Disposicion')),
                ('activa', models.BooleanField(default=False, verbose_name=b'ACTIVA')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name=b'Ini ')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name=b'Fecha Fin Ausencia')),
                ('codigo', models.CharField(max_length=32)),
                ('informe', models.TextField(default=b'Detalle designacion TD.....')),
            ],
            options={
                'db_table': 'dispos_gestionrh',
                'verbose_name_plural': 'Disposiciones Gestion RH',
            },
        ),
        migrations.CreateModel(
            name='Dispo_Junta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposicion', models.CharField(choices=[('LETP', 'Licencia Tiempo Prolongado'), ('PTDIF', 'Pase a Tarea Diferente'), ('LPEMB', 'Lic Proteccion Embarazo'), ('RTEGRO', 'Reintegro Tarea Habitual')], max_length=16, verbose_name=b'Disposicion')),
                ('activa', models.BooleanField(default=False, verbose_name=b'ACTIVA')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name=b'Ini ')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name=b'Fecha Fin Ausencia')),
                ('codigo', models.CharField(max_length=8)),
                ('informe', models.TextField(default=b'Detalle designacion TD.....')),
            ],
            options={
                'db_table': 'dispos_tdif',
                'verbose_name_plural': 'Disposiciones Tareas Diferentes',
            },
        ),
        migrations.CreateModel(
            name='Junta_realizada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField(default=False, verbose_name=b'CONS')),
                ('lugardejunta', models.CharField(choices=[('CESSO', 'Consultorio SSO'), ('CEART', 'Consultorio ART'), ('HPBLICO', 'Hospital Publico'), ('MOVIL', 'Movil')], max_length=16, verbose_name=b'LUGAR DE JUNTA')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name=b'Ini Ausencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name=b'Fecha Fin Ausencia')),
                ('codigo', models.CharField(max_length=16)),
                ('informe', models.TextField(default=b'Evaluacion Trabajador.....')),
                ('descripcion', models.TextField(default=b'Lic x ..')),
                ('ausencia_referida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ausencias.Ausencia_trb', verbose_name=b'Ausencia Vinculada')),
            ],
            options={
                'db_table': 'juntas_evaluacion',
                'verbose_name_plural': 'Juntas Medicas',
            },
        ),
        migrations.CreateModel(
            name='Resultado_junta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.TextField(default=b'Lic x ..')),
            ],
            options={
                'db_table': 'dictamenes_junta',
                'verbose_name_plural': 'Dictamenes de Junta ',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Ausencia_trb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'tipos_ausencias',
                'verbose_name_plural': 'Tipos de Ausencia ',
            },
        ),
    ]
