# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-01 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rechum', '0001_initial'),
        ('entornos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadependencia',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name=b'Responsable del area'),
        ),
        migrations.AddField(
            model_name='actagg',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Grupogestion', verbose_name=b'Grupo'),
        ),
        migrations.AddField(
            model_name='actagg',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'Sitio de Reunion'),
        ),
        migrations.AddField(
            model_name='actagg',
            name='participantes',
            field=models.ManyToManyField(to='rechum.Trabajador', verbose_name=b'Participantes'),
        ),
    ]
