# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-11 01:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechum', '0001_initial'),
        ('entornos', '0002_areadependencia_responsable'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActaGG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name=b'Fecha_Hora')),
                ('acta', models.TextField(default=b'Acta reunidos -----', verbose_name=b'Resumen de la reunion')),
            ],
        ),
        migrations.CreateModel(
            name='Grupogestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name=b'Nombre')),
                ('codigo', models.CharField(max_length=12, verbose_name=b'Codigo')),
            ],
            options={
                'verbose_name_plural': 'GruposGestion',
            },
        ),
        migrations.AddField(
            model_name='actagg',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Grupogestion', verbose_name=b'Grupo'),
        ),
        migrations.AddField(
            model_name='actagg',
            name='inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'Sitio de Reunion'),
        ),
        migrations.AddField(
            model_name='actagg',
            name='participantes',
            field=models.ManyToManyField(to='rechum.Trabajador', verbose_name=b'Participantes'),
        ),
    ]
