# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entornos', '0002_auto_20180501_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=36)),
                ('codigo', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'obscls',
                'verbose_name': 'Obra Social',
                'verbose_name_plural': 'Obras Sociales',
            },
        ),
    ]
