# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nacimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nsemanas', models.IntegerField(blank=True, default=36, null=True, verbose_name=b'N de semanas')),
                ('fecha_internacion_madre', models.DateTimeField(verbose_name=b'Fecha Internacion Madre')),
                ('fecha_nacimiento', models.DateTimeField(verbose_name=b'Fecha Nacimiento')),
                ('fecha_alta', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Solicitud')),
                ('cds_alta', models.CharField(choices=[(b'AM', b'Alta Medica'), (b'RETVOL', b'Retiro Voluntario'), (b'TRLDDRV', b'Traslado Derivacion')], default=b'AM', max_length=8, verbose_name=b'ModoAlta')),
                ('fecha_insert', models.DateField(auto_now=True)),
                ('tiponac', models.CharField(choices=[(b'PVAGNL', b'Parto Vaginal'), (b'CSAREA', b'Cesarea'), (b'I', b'no determinado')], default=b'PVAGNL', max_length=8, verbose_name=b'Modo Nacimiento')),
                ('sexo', models.CharField(choices=[(b'M', b'masculino'), (b'F', b'femenino'), (b'I', b'no determinado')], default=b'F', max_length=1, verbose_name=b'Sexo Nacido')),
                ('peso', models.IntegerField(default=300, verbose_name=b'Peso en Grs')),
                ('edadgest', models.IntegerField(default=38, verbose_name=b'Edad Gestacional-SEMANAS')),
                ('nacvivo', models.BooleanField(default=True, verbose_name=b'Nacido VIVO')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name=b'Comentarios')),
            ],
            options={
                'db_table': 'nacimientos',
                'verbose_name_plural': 'Nacimientos',
            },
        ),
        migrations.CreateModel(
            name='Patos_madre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=12)),
                ('descripcion', models.TextField(default=b'Descripcion ...')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'patos_mat',
                'verbose_name': 'Ptlgia Materna',
                'verbose_name_plural': 'Patologias Maternas',
            },
        ),
    ]
