# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-15 01:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('oytred', '0001_initial'),
        ('libronacs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nacimiento',
            name='dgs_madre',
            field=models.ManyToManyField(to='oytred.cie10', verbose_name=b'Diagns. Madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='madre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Paciente', verbose_name=b'Madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='patos_madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libronacs.Patos_madre'),
        ),
        migrations.AddField(
            model_name='nacimiento',
            name='xinternacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Internacion', verbose_name=b'Internacion'),
        ),
    ]
