# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-27 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import servicios.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ausencias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entornos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asigna_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name=b'Activo')),
                ('tipoasignacion', models.CharField(choices=[('REG', 'Regular'), ('KBT', 'Cubre Ausencia'), ('CTO', 'Contrato')], default=b'REG', max_length=12, verbose_name=b'Tipo Asignacion')),
                ('fecha_inicio', models.DateField(verbose_name=b'Fecha Inicio Actividad')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name=b'Fecha Fin Actividad')),
                ('modosemanal', models.CharField(choices=[('TLD', 'Todas las Semanas'), ('UDS', 'Semana x medio'), ('LAV', 'Rotativo'), ('XTR', 'ExtraOrdinario')], max_length=18, verbose_name=b'Frecuencia mensual')),
                ('horasxdia', models.IntegerField(verbose_name=b'Horas x Dia')),
                ('comentarios', models.TextField(blank=True, max_length=128, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('areadep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name=b'Area Responsable')),
                ('dds', models.ManyToManyField(to='entornos.Dds', verbose_name=b'DiasSemanales')),
            ],
            options={
                'db_table': 'asignalabs',
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones laborales',
            },
        ),
        migrations.CreateModel(
            name='Categoria_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.TextField(default=b'Descr....')),
            ],
            options={
                'db_table': 'mr_categorias',
                'verbose_name': 'Categoria ',
                'verbose_name_plural': 'Categorias Laborales',
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhoras', models.IntegerField(blank=True, null=True, verbose_name=b'N de horas  ')),
                ('fecha_inicio', models.DateTimeField(verbose_name=b'Fecha Inicio Actividad')),
                ('fecha_fin', models.DateTimeField(verbose_name=b'Fecha Finalizacion Actividad')),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Solicitud')),
                ('fecha_insert', models.DateField(auto_now=True)),
                ('fecha_cobro', models.DateTimeField(blank=True, null=True, verbose_name=b'FechaCobro')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name=b'Comentarios')),
            ],
            options={
                'db_table': 'contratos',
                'verbose_name_plural': 'Contratos Mensuales',
            },
        ),
        migrations.CreateModel(
            name='Dia_Sm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=12)),
                ('codigo', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'ddlasem',
                'verbose_name': 'Dia Semana',
                'verbose_name_plural': 'Dias de la Semana',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'especialidades',
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhoras', models.IntegerField(blank=True, null=True, verbose_name=b'N de horas ')),
                ('fecha_inicio', models.DateTimeField(default=servicios.models.default_hora_ini, verbose_name=b'Fecha Inicio Extension')),
                ('fecha_fin', models.DateTimeField(verbose_name=b'Fecha Finalizacion Actividad')),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Solicitud')),
                ('fecha_insert', models.DateField(auto_now=True)),
                ('fecha_cobro', models.DateTimeField(blank=True, null=True, verbose_name=b'FechaCobro')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name=b'Comentarios')),
                ('asignalab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Asigna_lab', verbose_name=b'Para cumplir Asignacion ')),
            ],
            options={
                'db_table': 'extensiones',
                'verbose_name_plural': 'Extensiones Horarias ',
            },
        ),
        migrations.CreateModel(
            name='Func_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=12)),
                ('descripcion', models.TextField(default=b'Descripcion ...')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'funclabs',
                'verbose_name': 'Funcion',
                'verbose_name_plural': 'Funciones Laborales',
            },
        ),
        migrations.CreateModel(
            name='Guardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigencia', models.BooleanField(default=True, verbose_name=b'Vigencia')),
                ('tipopresencia', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('DIF', 'Dif')], default=b'ACT', max_length=12, verbose_name=b'Tipo Presencial')),
                ('modo', models.CharField(choices=[('REG', 'Regular'), ('CBA', 'Cubre Ausencia')], default=b'ACT', max_length=12, verbose_name=b'Tipo Presencial')),
                ('responsabilidad', models.CharField(choices=[('J G', 'Jefe Dia'), ('Esp', 'Especialista'), ('DIF', 'Dif')], default=b'REG', max_length=12, verbose_name=b'Dia de la Semana')),
                ('fecha_inicio', models.DateTimeField(default=servicios.models.default_hora_ini, verbose_name=b'Fecha Inicio Actividad')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Fin Actividad')),
                ('comentarios', models.TextField(blank=True, max_length=128, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('espec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Especialidad', verbose_name=b'Esp')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'Institucion Referente')),
            ],
            options={
                'db_table': 'asignalabs',
                'verbose_name': 'Asignacion',
                'verbose_name_plural': 'Asignaciones laborales',
            },
        ),
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'profesiones',
                'verbose_name': 'Profesion',
                'verbose_name_plural': 'Profesiones',
            },
        ),
        migrations.CreateModel(
            name='Reemplazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nhoras', models.IntegerField(blank=True, null=True, verbose_name=b'N de horas ')),
                ('fecha_inicio', models.DateField(verbose_name=b'Fecha Inicio Actividad')),
                ('fecha_solicitud', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Solicitud')),
                ('fecha_insert', models.DateField(auto_now=True)),
                ('fecha_cobro', models.DateTimeField(blank=True, null=True, verbose_name=b'FechaCobro')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name=b'Comentarios')),
                ('asglabs', models.ManyToManyField(to='servicios.Asigna_lab', verbose_name=b'Modulo asignado')),
            ],
            options={
                'db_table': 'reemplazos',
                'verbose_name_plural': 'Reemplazos Mensual',
            },
        ),
        migrations.CreateModel(
            name='Registro_categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_vigencia', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=128, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Categoria_lab', verbose_name=b'Categoria registrada')),
            ],
            options={
                'db_table': 'registros_catgs',
                'verbose_name_plural': 'Registros de Categoria',
            },
        ),
        migrations.CreateModel(
            name='Registro_especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_vigencia', models.DateTimeField(blank=True, null=True, verbose_name=b'Fecha Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=128, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Especialidad', verbose_name=b'Especialidad registrada')),
            ],
            options={
                'db_table': 'registros_esps',
                'verbose_name_plural': 'Registros de Especialidad',
            },
        ),
        migrations.CreateModel(
            name='Registro_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_vigencia', models.DateField(blank=True, null=True, verbose_name=b'Fecha Inicio Vigencia')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name=b'Comentarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'registros_status',
                'verbose_name': 'Cambio Estado',
                'verbose_name_plural': ' Modificaciones de Estado ',
            },
        ),
        migrations.CreateModel(
            name='Status_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.TextField(default=b'Descr....')),
            ],
            options={
                'db_table': 'mr_status',
                'verbose_name': 'Estado Laboral',
                'verbose_name_plural': 'Estados Laborales',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('tpodoc', models.CharField(default=b'DNI', max_length=5)),
                ('nrodoc', models.IntegerField(default=1)),
                ('ncuitl', models.CharField(blank=True, max_length=24, null=True)),
                ('matricula', models.CharField(blank=True, max_length=16, null=True)),
                ('imgtrb', models.ImageField(blank=True, help_text=b'Archivo de imagen...', null=True, upload_to=b'fototrb/%Y/%m')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name=b'Fecha de Nacimiento')),
                ('domicilio', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, default=b'341', max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'E Mail')),
                ('cuit', models.CharField(blank=True, max_length=16, null=True)),
                ('activo', models.NullBooleanField(default=True, verbose_name=b'Activo')),
                ('mr_fecha_ingreso', models.DateField(blank=True, null=True, verbose_name=b'Fecha Ingreso MR')),
                ('mr_legajo', models.IntegerField(blank=True, null=True, verbose_name=b'N de Legajo')),
                ('xlreparticion', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Reparticion')),
                ('xltipoemp', models.CharField(blank=True, max_length=32, null=True)),
                ('xlcaliflab', models.CharField(blank=True, max_length=32, null=True, verbose_name=b'Calificacion ')),
                ('xltitulo', models.CharField(blank=True, max_length=32, null=True)),
                ('mrmapid', models.IntegerField(blank=True, editable=False, null=True)),
                ('mrpersonaid', models.IntegerField(blank=True, editable=False, null=True)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name=b'Comentarios')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateField(auto_now=True, null=True)),
                ('especialidad_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp1', to='servicios.Especialidad', verbose_name=b'Especialidad principal')),
                ('especialidad_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp2', to='servicios.Especialidad', verbose_name=b'Especialidad Dos')),
                ('especialidad_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp3', to='servicios.Especialidad', verbose_name=b'Especialidad Tres')),
                ('especialidad_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp4', to='servicios.Especialidad', verbose_name=b'Especialidad Cuatro')),
                ('mr_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Categoria_lab', verbose_name=b'Categoria Municipal')),
                ('mr_statuslab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Status_lab', verbose_name=b'Condicion Laboral')),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Profesion', verbose_name=b'Profesion')),
            ],
            options={
                'ordering': ['apellido'],
                'db_table': 'trabajadores',
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores Salud',
            },
        ),
        migrations.AddField(
            model_name='registro_status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Status_lab', verbose_name=b'Estado Laboral registrado'),
        ),
        migrations.AddField(
            model_name='registro_status',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador'),
        ),
        migrations.AddField(
            model_name='registro_status',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='registro_especialidad',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador'),
        ),
        migrations.AddField(
            model_name='registro_especialidad',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='registro_categorias',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador'),
        ),
        migrations.AddField(
            model_name='registro_categorias',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='reemplazo',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador'),
        ),
        migrations.AddField(
            model_name='reemplazo',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Profesion', verbose_name=b'PROFESION'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Servicio', verbose_name=b'Servicio Servicio Referente'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='trabajador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='extension',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador'),
        ),
        migrations.AddField(
            model_name='extension',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='extension',
            name='xausenciatrab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ausencias.Ausencia_trb', verbose_name=b'Cobertura Ausencia '),
        ),
        migrations.AddField(
            model_name='contrato',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador Contratado'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='xausenciatrab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ausencias.Ausencia_trb', verbose_name=b'Cobertura Ausencia '),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='espec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='servicios.Especialidad', verbose_name=b'Esp'),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='funcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Func_lab', verbose_name=b'Funcion'),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name=b'Institucion Referente'),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='profesion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Profesion', verbose_name=b'PROFESION'),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Servicio', verbose_name=b'Servicio Servicio Referente'),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Trabajador', verbose_name=b'Trabajador'),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'Registrado por'),
        ),
        migrations.AddField(
            model_name='asigna_lab',
            name='xausenciatrab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ausencias.Ausencia_trb', verbose_name=b'Cubre Ausencia '),
        ),
    ]
