# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 18:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reemplazo',
            name='usuario_registro',
        ),
        migrations.AlterField(
            model_name='reemplazo',
            name='areadep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name=b'Resp Reemplazo'),
            preserve_default=False,
        ),
    ]
