# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20180518_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='reemplazo',
            name='msgvalidacion',
            field=models.CharField(blank=True, default=b'Valmsg..', max_length=512, null=True, verbose_name=b'Msg Revision'),
        ),
        migrations.AddField(
            model_name='reemplazo',
            name='validado',
            field=models.BooleanField(default=False, verbose_name=b'Validado SRVSS'),
        ),
    ]
