# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-31 11:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_auto_20180520_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardia',
            name='duracionhs',
            field=models.IntegerField(default=24, verbose_name=b'N hS'),
        ),
        migrations.AddField(
            model_name='guardia',
            name='hora_inicio',
            field=models.TimeField(default=django.utils.timezone.now, verbose_name=b'HORA INICIO'),
            preserve_default=False,
        ),
    ]
