# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 21:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import zcons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cie10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupodg', models.CharField(blank=True, choices=[('NC', 'no clasificado'), ('TRMT', 'traumatologico'), ('RSPT', 'respiratorio'), ('GSTN', 'gastrointestinal'), ('NFUR', 'nefrourologico'), ('SNCO', 'sistema nervioso'), ('CVSC', 'cardiovascular')], max_length=4, null=True)),
                ('categoria', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('codigo', models.CharField(default='ABC1234', max_length=10)),
                ('comentarios', models.CharField(blank=True, max_length=128, null=True)),
                ('habilitado', models.NullBooleanField(default=False, verbose_name='Habilitado')),
            ],
            options={
                'db_table': 'zcons_cie10',
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_afiliado', models.CharField(blank=True, max_length=12, null=True, verbose_name='N de Afiliado')),
                ('cod_cons', models.CharField(default='CODIGO', max_length=16, verbose_name='CODIGO de Consulta')),
                ('coseguro', models.CharField(default='Coseguro $', max_length=128, verbose_name='Coseguro')),
                ('fecha_consulta', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Consulta')),
                ('fecha_recitacion', models.DateField(blank=True, null=True, verbose_name='Fecha Recitacion')),
                ('evaluacion', models.TextField(default=zcons.models.diayhora, verbose_name='Evaluacion')),
                ('indicaciones', models.TextField(default='Indicaciones. ...Medicacion....Laboratorio.....')),
                ('hora_consulta', models.TimeField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('NDTM', 'no determinado'), ('PRV', 'Primera Vez'), ('ULT', 'Ulterior')], default='PRV', max_length=4, null=True)),
                ('informe', models.TextField(default='Comentarios...', verbose_name='Texto Consulta')),
            ],
            options={
                'ordering': ['paciente__apellido'],
                'db_table': 'zcons_consultas',
                'verbose_name': 'Consulta',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Diagnostico')),
                ('grupodg', models.CharField(blank=True, choices=[('NC', 'no clasificado'), ('TRMT', 'traumatologico'), ('RSPT', 'respiratorio'), ('GSTN', 'gastrointestinal'), ('NFUR', 'nefrourodjango.contrib.contenttypeslogico'), ('SNCO', 'sistema nervioso'), ('CVSC', 'cardiovascular')], default='NC', max_length=4, null=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=12)),
                ('comentarios', models.CharField(blank=True, max_length=128, null=True)),
                ('habilitado', models.NullBooleanField(default=False)),
                ('cie10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zcons.cie10', verbose_name='ref Cie 10')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_diagnosticos',
                'verbose_name': 'Diagnostico',
                'verbose_name_plural': 'Diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Droga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_drogas',
                'verbose_name': 'Droga',
                'verbose_name_plural': 'Drogas',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'zcons_especialidades',
            },
        ),
        migrations.CreateModel(
            name='GruposVrb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='GrupoV....', max_length=56, verbose_name='Nombre Grupo')),
                ('codigo', models.CharField(default='GVLAB', max_length=10, verbose_name='Codigo Grupo')),
            ],
            options={
                'db_table': 'zcons_gruposvrb',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('codigo', models.CharField(max_length=8)),
                ('domicilio', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comentarios', models.TextField(blank=True, default='N', null=True)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_instituciones',
                'verbose_name': 'Institucion',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_localidades',
                'verbose_name': 'Localidad',
            },
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=36)),
                ('descripcion', models.CharField(max_length=124)),
                ('drogas', models.ManyToManyField(blank=True, to='zcons.Droga', verbose_name='Componente')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_medicaciones',
                'verbose_name': 'Medicacion',
                'verbose_name_plural': 'Medicaciones',
            },
        ),
        migrations.CreateModel(
            name='Obrasocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'zcons_obscs',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('tipo_documento', models.CharField(choices=[('DU', 'documento unico'), ('ND', 'no determinado'), ('LE', 'libreta de enrolamiento'), ('LC', 'libreta c\xedvica'), ('PA', 'pasaporte'), ('CE', 'c\xe9dula federal'), ('CM', 'certificado migratorio'), ('ET', 'en tr\xe1mite')], default='DU', max_length=2)),
                ('numero_documento', models.IntegerField(default=0, verbose_name='N de Doc ')),
                ('doc_cons', models.BooleanField(default=False, verbose_name='Doc Consolidado')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('estado_civil', models.CharField(blank=True, choices=[('ND', 'no determinado'), ('SO', 'soltero'), ('CA', 'casado'), ('VI', 'viudo'), ('SL', 'separado legal'), ('SH', 'separado de hecho'), ('DI', 'divorciado'), ('CO', 'conviviente'), ('PI', 'pirata')], max_length=2, null=True)),
                ('sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino'), ('T', 'Transexual'), ('I', 'no determinado')], default='I', max_length=1)),
                ('nacionalidad', models.CharField(choices=[('ND', 'No definido'), ('AFG', 'Afganist\xe1n'), ('ALA', '\xc5land'), ('ALB', 'Albania'), ('DEU', 'Alemania'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('AIA', 'Anguila'), ('ATA', 'Ant\xe1rtida'), ('ATG', 'Antigua y Barbuda'), ('ANT', 'Antillas Neerlandesas'), ('SAU', 'Arabia Saudita'), ('DZA', 'Argelia'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ABW', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaiy\xe1n'), ('BHS', 'Bahamas'), ('BHR', 'Bahr\xe9in'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BEL', 'B\xe9lgica'), ('BLZ', 'Belice'), ('BEN', 'Ben\xedn'), ('BMU', 'Bermudas'), ('BLR', 'Bielorrusia'), ('MMR', 'Birmania'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia y Herzegovina'), ('BWA', 'Botsuana'), ('BVT', 'Noruega Isla Bouvet'), ('BRA', 'Brasil'), ('BRN', 'Brun\xe9i'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('BTN', 'But\xe1n'), ('CPV', 'Cabo Verde'), ('CYM', 'Islas Caim\xe1n'), ('KHM', 'Camboya'), ('CMR', 'Camer\xfan'), ('CAN', 'Canad\xe1'), ('CAF', 'Rep\xfablica Centroafricana'), ('TCD', 'Chad'), ('CZE', 'Rep\xfablica Checa'), ('CHL', 'Chile'), ('CHN', 'China'), ('CYP', 'Chipre'), ('CCK', 'Islas Cocos'), ('COL', 'Colombia'), ('COM', 'Comoras'), ('COG', 'Rep\xfablica del Congo'), ('COD', 'Rep\xfablica Democr\xe1tica del Congo'), ('COK', 'Islas Cook'), ('PRK', 'Corea del Norte'), ('KOR', 'Corea del Sur'), ('CIV', 'Costa de Marfil'), ('CRI', 'Costa Rica'), ('HRV', 'Croacia'), ('CUB', 'Cuba'), ('DNK', 'Dinamarca'), ('DMA', 'Dominica'), ('DOM', 'Rep\xfablica Dominicana'), ('ECU', 'Ecuador'), ('EGY', 'Egipto'), ('SLV', 'El Salvador'), ('ARE', 'Emiratos \xc1rabes Uniclass Pacdos'), ('ERI', 'Eritrea'), ('SVK', 'Eslovaquia'), ('SVN', 'Eslovenia'), ('ESP', 'Espa\xf1a'), ('USA', 'Estados Unidos'), ('UMI', 'Islas ultramarinas de Estados Unidos'), ('EST', 'Estonia'), ('ETH', 'Etiop\xeda'), ('FRO', 'Islas Feroe'), ('PHL', 'Filipinas'), ('FIN', 'Finlandia'), ('FJI', 'Fiyi'), ('FRA', 'Francia'), ('GAB', 'Gab\xf3n'), ('GMB', 'Gambia'), ('GEO', 'Georgia'), ('SGS', 'Islas Georgias del Sur y Sandwich del Sur'), ('GHA', 'Ghana'), ('GIB', 'Gibraltar'), ('GRD', 'Granada'), ('GRC', 'Grecia'), ('GRL', 'Groenlandia'), ('GLP', 'Guadalupe'), ('GUM', 'Guam'), ('GTM', 'Guatemala'), ('GUF', 'Guayana Francesa'), ('GGY', 'Guernsey'), ('GIN', 'Guinea'), ('GNQ', 'Guinea Ecuatorial'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Hait\xed'), ('HMD', 'Australia Islas Heard y McDonald'), ('HND', 'Honduras'), ('HKG', 'Hong Kong'), ('HUN', 'Hungr\xeda'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Ir\xe1n'), ('IRQ', 'Iraq'), ('IRL', 'Irlanda'), ('ISL', 'Islandia'), ('ISR', 'Israel'), ('ITA', 'Italia'), ('JAM', 'Jamaica'), ('JPN', 'Jap\xf3n'), ('JEY', 'Jersey'), ('JOR', 'Jordania'), ('KAZ', 'Kazajist\xe1n'), ('KEN', 'Kenia'), ('KGZ', 'Kirguist\xe1n'), ('KIR', 'Kiribati'), ('KWT', 'Kuwait'), ('LAO', 'Laos'), ('LSO', 'Lesoto'), ('LVA', 'Letonia'), ('LBN', 'L\xedbano'), ('LBR', 'Liberia'), ('LBY', 'Libia'), ('LIE', 'Liechtenstein'), ('LTU', 'Lituania'), ('LUX', 'Luxemburgo'), ('MAC', 'Macao'), ('MKD', 'Rep\xfablica de Macedonia'), ('MDG', 'Madagascar'), ('MYS', 'Malasia Malasia'), ('MWI', 'Malaui'), ('MDV', 'Maldivas'), ('MLI', 'Mal\xed'), ('MLT', 'Malta'), ('FLK', 'Islas Malvinas'), ('IMN', 'Isla de Man'), ('MNP', 'Islas Marianas del Norte'), ('MAR', 'Marruecos Marruecos'), ('MHL', 'Islas Marshall'), ('MTQ', 'Martinica'), ('MUS', 'Mauricio'), ('MRT', 'Mauritania'), ('MYT', 'Mayotte'), ('MEX', 'M\xe9xico M\xe9xico'), ('FSM', 'Micronesia'), ('MDA', 'Moldavia'), ('MCO', 'M\xf3naco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MSR', 'Montserrat'), ('MOZ', 'Mozambique'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('CXR', 'Isla de Navidad'), ('NPL', 'Nepal Nepal'), ('NIC', 'Nicaragua'), ('NER', 'N\xedger'), ('NGA', 'Nigeria'), ('NIU', 'Niue'), ('NFK', 'Norfolk'), ('NOR', 'Noruega'), ('NCL', 'Nueva Caledonia'), ('NZL', 'Nueva Zeclass PracticaQlanda'), ('OMN', 'Om\xe1n'), ('NLD', 'Pa\xedses Bajos'), ('PAK', 'Pakist\xe1n'), ('PLW', 'Palaos'), ('PSE', 'Territorios palestinos'), ('PAN', 'Panam\xe1'), ('PNG', 'Pap\xfaa Nueva Guinea'), ('PRY', 'Paraguay'), ('PER', 'Per\xfa'), ('PCN', 'Islas Pitcairn'), ('PYF', 'Polinesia Francesa'), ('POL', 'Polonia'), ('PRT', 'Portugal'), ('PRI', 'Puerto Rico'), ('QAT', 'Qatar'), ('GBR', 'Reino Unido'), ('REU', 'Reuni\xf3n'), ('RWA', 'Ruanda'), ('ROU', 'Rumania'), ('RUS', 'Rusia'), ('ESH', 'Rep\xfablica \xc1rabe Saharaui Democr\xe1tica'), ('SLB', 'Islas Salom\xf3n'), ('WSM', 'Samoa'), ('ASM', 'Samoa Americana'), ('BLM', 'San Bartolom\xe9'), ('KNA', 'San Crist\xf3bal y Nieves'), ('SMR', 'San Marino'), ('MAF', 'Saint-Martin'), ('SPM', 'San Pedro y Miquel\xf3n'), ('VCT', 'San Vicente y las Granadinas'), ('AFG', 'Afganist\xe1n'), ('ALA', '\xc5land'), ('ALB', 'Albania'), ('DEU', 'Alemania'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('AIA', 'Anguila'), ('ATA', 'Ant\xe1rtida'), ('ATG', 'Antigua y Barbuda'), ('ANT', 'Antillas Neerlandesas'), ('SAU', 'Arabia Saudita'), ('DZA', 'Argelia'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ABW', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaiy\xe1n'), ('SHN', 'Santa Helena'), ('LCA', 'Santa Luc\xeda'), ('STP', 'Santo Tom\xe9 y Pr\xedncipe'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leona'), ('SGP', 'Singapur'), ('SYR', 'Siria'), ('SOM', 'Somalia'), ('LKA', 'Sri Lanka'), ('SWZ', 'Suazilandia'), ('ZAF', 'Sud\xe1frica'), ('SDN', 'Sud\xe1n'), ('SWE', 'Suecia'), ('CHE', 'Suiza'), ('SUR', 'Surinam'), ('SJM', 'Svalbard y Jan Mayen'), ('THA', 'Tailandia'), ('TWN', 'Taiw\xe1n'), ('TZA', 'Tanzania'), ('TJK', 'Tayikist\xe1n'), ('IOT', 'Territorio Brit\xe1nico del Oc\xe9ano \xcdndico'), ('ATF', 'Territorios Australes Franceses'), ('TLS', 'Timor Oriental'), ('TGO', 'Togo'), ('TKL', 'Tokelau'), ('TON', 'Tonga'), ('TTO', 'Trinidad y Tobago'), ('TUN', 'T\xfanez T\xfanez'), ('TCA', 'Islas Turcas y Caicos'), ('TKM', 'Turkmenist\xe1n'), ('TUR', 'Turqu\xeda'), ('TUV', 'Tuvalu'), ('UKR', 'Ucrania'), ('UGA', 'Uganda'), ('URY', 'Uruguay'), ('UZB', 'Uzbekist\xe1n'), ('VUT', 'Vanuatu'), ('VAT', 'Ciudad del Vaticano'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('VGB', 'Islas V\xedrgenes Brit\xe1nicas'), ('VIR', 'Islas V\xedrgenes Estadounidenses'), ('WLF', 'Wallis y Futuna'), ('YEM', 'Yemen'), ('DJI', 'Yibuti'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabue')], default='ARG', max_length=36)),
                ('provincia', models.CharField(choices=[('01', 'CAPITAL FEDERAL'), ('02', 'BUENOS AIRES'), ('03', 'CATAMARCA'), ('04', 'CORDOBA'), ('05', 'CORRIENTES'), ('06', 'ENTRE RIOS'), ('07', 'JUJUY'), ('08', 'LA RIOJA'), ('09', 'MENDOZA'), ('10', 'SALTA'), ('11', 'SAN JUAN'), ('12', 'SAN LUIS'), ('13', 'SANTA FE'), ('14', 'SANTIAGO DEL ESTERO'), ('15', 'TUCUMAN'), ('16', 'CHACO'), ('17', 'CHUBUT'), ('18', 'FORMOSA'), ('19', 'LA PAMPA'), ('20', 'MISIONES'), ('21', 'NEUQUEN'), ('22', 'RIO NEGRO'), ('23', 'SANTA CRUZ'), ('24', 'TIERRA DEL FUEGO')], default='13', max_length=2)),
                ('domicilio', models.CharField(blank=True, max_length=128)),
                ('telefono', models.CharField(default='341 .....', max_length=96)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('domicilio_trabajo', models.CharField(blank=True, default='No Registrado', max_length=128)),
                ('comentarios', models.TextField(blank=True, default='No comentarios', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zcons.Localidad')),
            ],
            options={
                'ordering': ['apellido'],
                'db_table': 'zcons_pacientes',
                'verbose_name': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='PracticaQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=36)),
                ('grupopq', models.CharField(choices=[('NC', 'no clasificado'), ('CM', 'Clinicas'), ('CVS', 'Quirurgicas'), ('DG', 'Diagnosticas')], default='NC', max_length=6)),
                ('descripcion', models.CharField(max_length=128)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'zcons_practicas',
            },
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(default='1 ampolla...1 comprimido ...250 mg', max_length=124)),
                ('ndosis', models.IntegerField(default=1, verbose_name='Numero total')),
                ('periodo', models.IntegerField(default=8, verbose_name='Periodo en Horas')),
                ('fecha_ini', models.DateField(default=datetime.datetime.today, verbose_name='Fin medicacion')),
                ('detalle', models.CharField(default='D', max_length=512, verbose_name='Detalle prescripcion.....')),
            ],
            options={
                'ordering': ['paciente__apellido'],
                'db_table': 'zcons_prescripciones',
                'verbose_name': 'Prescripcion',
                'verbose_name_plural': 'Prescripciones',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32, verbose_name='Nombre Presntcn')),
                ('codigo', models.CharField(max_length=16)),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_presentaciones',
                'verbose_name': 'Presentacion',
                'verbose_name_plural': 'Presentaciones FRM',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=28, verbose_name='Apellido')),
                ('nombre', models.CharField(max_length=28, verbose_name='Nombre')),
                ('tipodoc', models.CharField(default='DNI', max_length=5, verbose_name='Tipo Documento')),
                ('nrodoc', models.IntegerField(default='0', verbose_name='Numero DNI')),
                ('matricula', models.CharField(blank=True, default='ABC123', max_length=16, null=True, verbose_name='Matricula')),
                ('etiqueta', models.CharField(blank=True, default='Etiq..', max_length=128, null=True, verbose_name='Etiqueta')),
                ('domicilio', models.CharField(blank=True, max_length=128, null=True, verbose_name='Domicilio')),
                ('telefono', models.CharField(blank=True, max_length=52, null=True, verbose_name='Telefonos')),
                ('email', models.EmailField(default='algo_yotracosa@gmail.com', max_length=254, verbose_name='Dir de E Mail')),
                ('activo', models.BooleanField(default=True)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('especialidad', models.ManyToManyField(blank=True, to='zcons.Especialidad', verbose_name='Especialidad')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_profesionales',
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(default='1 ampolla...1 comprimido ...250 mg', max_length=124)),
                ('ndosis', models.IntegerField(default=1, verbose_name='Numero total')),
                ('periodo', models.IntegerField(default=8, verbose_name='Periodo en Horas')),
                ('fecha_receta', models.DateField(default=datetime.datetime.now, verbose_name='Fecha RP')),
                ('fecha_ini', models.DateField(default=datetime.datetime.today, verbose_name='Fin medicacion')),
                ('detalle', models.TextField(default='R/P', max_length=512, verbose_name='R/P')),
                ('forma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Presentacion', verbose_name='Presentacion')),
                ('medicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Medicacion', verbose_name='Medicamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Paciente', verbose_name='Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Profesional', verbose_name='Profesional')),
            ],
            options={
                'ordering': ['paciente__apellido'],
                'db_table': 'zcons_recetas',
                'verbose_name': 'Receta',
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='Reg_variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reg', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Resultado P Ex')),
                ('valorvrb', models.CharField(default='ABC123...', max_length=64, verbose_name='Valor')),
                ('comentarios', models.CharField(default='Coment....', max_length=128, verbose_name='Comentario')),
            ],
            options={
                'ordering': ['paciente__apellido'],
                'db_table': 'zcons_reg_vrbles',
                'verbose_name': 'Registro VRB',
                'verbose_name_plural': 'RegsV',
            },
        ),
        migrations.CreateModel(
            name='Solic_labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha Solicitud')),
            ],
            options={
                'ordering': ['fecha'],
                'db_table': 'zcons_solic_labs',
                'verbose_name': 'Solic de Examenes',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='..vg..Presion Arterial..gLICEMIa..', max_length=54, verbose_name='Nombre del Parametro')),
                ('codigo', models.CharField(default='Codigo123........', max_length=28, verbose_name='Codigo')),
                ('comentarios', models.CharField(default='Valores Normales hasta .....', max_length=256, verbose_name='Comentarios')),
                ('grupo_variable', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='zcons.GruposVrb', verbose_name='Grupo VB')),
            ],
            options={
                'ordering': ['nombre'],
                'db_table': 'zcons_variables',
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.AddField(
            model_name='solic_labs',
            name='examenes',
            field=models.ManyToManyField(to='zcons.Variable', verbose_name='Examenes'),
        ),
        migrations.AddField(
            model_name='solic_labs',
            name='obrasocial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zcons.Obrasocial', verbose_name='Obra Social'),
        ),
        migrations.AddField(
            model_name='solic_labs',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='solic_labs',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Profesional', verbose_name='Prof Solicitante'),
        ),
        migrations.AddField(
            model_name='reg_variable',
            name='nomvrb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Variable', verbose_name='Variable '),
        ),
        migrations.AddField(
            model_name='reg_variable',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='prescripcion',
            name='forma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Presentacion', verbose_name='Presentacion'),
        ),
        migrations.AddField(
            model_name='prescripcion',
            name='medicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Medicacion', verbose_name='Medicamento'),
        ),
        migrations.AddField(
            model_name='prescripcion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='prescripcion',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Profesional', verbose_name='Profesional'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagconsB', to='zcons.Diagnostico', verbose_name='Dg B'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagconsC', to='zcons.Diagnostico', verbose_name='Dg C'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico_D',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagconsD', to='zcons.Diagnostico', verbose_name='Dg D'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='diagnostico_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticoP', to='zcons.Diagnostico', verbose_name='Diagnostico'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Institucion', verbose_name='Institucion'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='interconsultante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prof_consultante', to='zcons.Profesional', verbose_name='PEDIDA X'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='obra_social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zcons.Obrasocial', verbose_name='Obra Social'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zcons.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='practica_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaB', to='zcons.PracticaQ'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='practica_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaC', to='zcons.PracticaQ'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='practica_D',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaD', to='zcons.PracticaQ'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='practica_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaP', to='zcons.PracticaQ'),
        ),
        migrations.AddField(
            model_name='consulta',
            name='prof',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prof_consultor', to='zcons.Profesional', verbose_name='Consultor'),
        ),
    ]
