# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-06 13:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entornos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ausencia_trb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generavacgen', models.BooleanField(default=False, verbose_name='Vac Genuina')),
                ('solicita_cobertura', models.BooleanField(default=False, verbose_name='X Cubrir')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Ini Ausencia')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Ausencia')),
                ('fecha_insert', models.DateField(auto_now=True)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('areadep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name='Area Dep')),
            ],
            options={
                'db_table': 'ausencias_trbs',
                'verbose_name': 'Ausencia TRB',
                'verbose_name_plural': 'Ausencias de Personal',
            },
        ),
        migrations.CreateModel(
            name='Categoria_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.TextField(default='Descr....')),
            ],
            options={
                'db_table': 'mr_categorias',
                'verbose_name': 'Categoria ',
                'verbose_name_plural': 'Categorias Laborales',
            },
        ),
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre Oficial....', max_length=64, verbose_name='Nombre')),
                ('activo', models.BooleanField()),
                ('codigo', models.CharField(default='Codigo....', max_length=32, verbose_name='Codigo')),
                ('tipo', models.CharField(choices=[('SIM', 'Seleccion Interna Municipal'), ('SAMP', 'Seleccion Abierta Municipalidad Provincia'), ('CAB', 'Concurso Abierto'), ('XTR', 'ExtraOrdinario')], default='SELECCION INTERNA MUNICIPAL', max_length=12, verbose_name='Tipo CONCURSO')),
                ('fecha_promocion', models.DateField(verbose_name='Fecha Promocion')),
                ('fecha_publicacion_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha Publicacion')),
                ('fecha_ini_entrevistas', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Entrevistas')),
                ('fecha_ini_examenes', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Examen')),
                ('fecha_recepcion_documentacion', models.DateField(blank=True, null=True, verbose_name='Fecha Recepcion Documentacion')),
                ('fecha_publicacion_resultados', models.DateField(blank=True, null=True, verbose_name='Fecha Publicacion Resultado')),
                ('fecha_fin_validez', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Validez Orden de Merito')),
                ('comentarios', models.TextField(blank=True, max_length=256, null=True, verbose_name='Explicitacion promocion')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('areadep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name='Area Responsable')),
                ('espec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Especialidad', verbose_name='Especialidad')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Inst')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Profesion', verbose_name='Profesion')),
            ],
            options={
                'db_table': 'concurso',
                'verbose_name': 'Concurso',
                'verbose_name_plural': 'Concursos',
            },
        ),
        migrations.CreateModel(
            name='DispoDesiDec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre Oficial....', max_length=64, verbose_name='Nombre')),
                ('activo', models.BooleanField()),
                ('codigo', models.CharField(default='Codigo....', max_length=32, verbose_name='Codigo')),
                ('tipo', models.CharField(choices=[('DSPCION', 'Disposicion'), ('RSLCION', 'Resolucion'), ('DCRTO', 'Decreto'), ('XTR', 'ExtraOrdinario')], default='SELECCION INTERNA MUNICIPAL', max_length=12, verbose_name='Tipo CONCURSO')),
                ('fecha_ini_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Publicacion')),
                ('textod', models.TextField(blank=True, null=True, verbose_name='Texto Disposicion')),
                ('comentarios', models.TextField(blank=True, max_length=256, null=True, verbose_name='Explicitacion ')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('areadep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name='Area Responsable')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Inst')),
            ],
            options={
                'db_table': 'decresodispos',
                'verbose_name': 'DCRSOLDISPO',
                'verbose_name_plural': 'DispoResoDecres',
            },
        ),
        migrations.CreateModel(
            name='Junta_medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmada', models.BooleanField(default=False, verbose_name='CONS')),
                ('lugardejunta', models.CharField(choices=[('CESSO', 'Consultorio SSO'), ('CEART', 'Consultorio ART'), ('HPBLICO', 'Hospital Publico'), ('MOVIL', 'Movil')], max_length=16, verbose_name='LUGAR DE JUNTA')),
                ('fecha_evaluacion', models.DateField(blank=True, null=True, verbose_name='Fecha Evaluacion')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha Fin Ausencia')),
                ('codigo', models.CharField(max_length=16)),
                ('informe', models.TextField(default='Evaluacion Trabajador.....')),
                ('descripcion', models.TextField(default='Lic x ..')),
                ('ausencia_orig_referida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Ausencia_trb', verbose_name='Ausencia Vinculada')),
                ('diagnostico_a', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgj_a', to='entornos.ciediez', verbose_name='Diagnostico Principal')),
                ('diagnostico_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgj_b', to='entornos.ciediez', verbose_name='Diagnostico B')),
                ('diagnostico_c', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgj_c', to='entornos.ciediez', verbose_name='Diagnostico C')),
                ('diagnostico_d', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dgj_d', to='entornos.ciediez', verbose_name='Diagnostico D')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Institucion ')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_categorias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_vigencia', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=128, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechum.Categoria_lab', verbose_name='Categoria registrada')),
            ],
            options={
                'db_table': 'registros_catgs',
                'verbose_name_plural': 'Registros de Categoria',
            },
        ),
        migrations.CreateModel(
            name='Registro_especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_vigencia', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=128, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Especialidad', verbose_name='Especialidad registrada')),
            ],
            options={
                'db_table': 'registros_esps',
                'verbose_name_plural': 'Registros de Especialidad',
            },
        ),
        migrations.CreateModel(
            name='Registro_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini_vigencia', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio Vigencia')),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'registros_status',
                'verbose_name': 'Cambio Estado',
                'verbose_name_plural': ' Modificaciones de Estado ',
            },
        ),
        migrations.CreateModel(
            name='Resultado_junta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.TextField(default='Lic x ..')),
            ],
            options={
                'db_table': 'resultados_jmedica',
                'verbose_name_plural': 'Resultados Junta Medica',
            },
        ),
        migrations.CreateModel(
            name='Solic_modif_trb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre Oficial....', max_length=64, verbose_name='Nombre')),
                ('activo', models.BooleanField()),
                ('codigo', models.CharField(default='Codigo....', max_length=32, verbose_name='Codigo')),
                ('tipo', models.CharField(choices=[('TRLDS', 'Traslados'), ('TDIFS', 'Tareas Diferentes'), ('REDHOR', 'Reducciones Horarias'), ('LSGS', 'Licencia sin Goce Haberes')], default='TRLDS', max_length=12, verbose_name='Tipo CONCURSO')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha Solicitud')),
                ('comentarios', models.TextField(blank=True, max_length=256, null=True, verbose_name='Explicitacion promocion')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('areadep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name='Area Responsable')),
                ('espec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Especialidad', verbose_name='Especialidad')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Inst')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Profesion', verbose_name='Profesion')),
            ],
            options={
                'db_table': 'solics_modif_trb',
                'verbose_name': 'SOLICITUD CAMBIO',
                'verbose_name_plural': 'Solicitudes de Cambio',
            },
        ),
        migrations.CreateModel(
            name='Solic_Rhum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha I')),
                ('horasxdia', models.IntegerField(verbose_name='Horas x Dia')),
                ('comentarios', models.TextField(blank=True, max_length=128, null=True)),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('areadep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name='Area Responsable')),
                ('concursofuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Concurso', verbose_name='Prop x Concurso')),
                ('espec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Especialidad', verbose_name='Especialidad')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Inst')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Profesion', verbose_name='Profesion')),
            ],
            options={
                'db_table': 'solicits_rhum',
                'verbose_name': 'Solicitud RHUM',
                'verbose_name_plural': 'Solicitudes Recurso Humano',
            },
        ),
        migrations.CreateModel(
            name='Status_lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.TextField(default='Descr....')),
            ],
            options={
                'db_table': 'mr_status',
                'verbose_name': 'Estado Laboral',
                'verbose_name_plural': 'Estados Laborales',
            },
        ),
        migrations.CreateModel(
            name='Tarea_diferente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Designacion Tarea Diferente....', max_length=64, verbose_name='Nombre')),
                ('activo', models.BooleanField()),
                ('codigo', models.CharField(default='Codigo....', max_length=32, verbose_name='Codigo')),
                ('tipo', models.CharField(choices=[('TEMPL', 'Temportal'), ('DFTVA', 'Definitiva'), ('EOBSN', 'En Observacion'), ('XTR', 'ExtraOrdinario')], default='SELECCION INTERNA MUNICIPAL', max_length=12, verbose_name='Tipo CONCURSO')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha Asignacion')),
                ('fecha_terminacion', models.DateField(blank=True, null=True, verbose_name='Fecha Terminacion')),
                ('fecha_revision', models.DateField(blank=True, null=True, verbose_name='Fecha Revision')),
                ('detalle', models.TextField(blank=True, max_length=256, null=True, verbose_name='Comentarios')),
                ('fecha_registro', models.DateField(auto_now=True)),
                ('areadep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Areadependencia', verbose_name='Area Responsable')),
                ('espec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Especialidad', verbose_name='Especialidad')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Inst')),
                ('profesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entornos.Profesion', verbose_name='Profesion')),
            ],
            options={
                'db_table': 'asgtdifs',
                'verbose_name': 'Asg Tarea Diferente',
                'verbose_name_plural': 'Tareas Diferentes',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Ausencia_trb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'tipos_ausencias',
                'verbose_name_plural': 'Tipos de Ausencia ',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('depend', models.CharField(choices=[('MUNI', 'Municipalidad'), ('PROV', 'Provincia')], default='MUNI', max_length=16, verbose_name='Dependencia')),
                ('tpodoc', models.CharField(default='DNI', max_length=5)),
                ('nrodoc', models.IntegerField(default=1)),
                ('ncuitl', models.CharField(blank=True, max_length=24, null=True)),
                ('matricula', models.CharField(blank=True, max_length=16, null=True)),
                ('imgtrb', models.ImageField(blank=True, help_text='Archivo de imagen...', null=True, upload_to='fototrb/%Y/%m')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('domicilio', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, default='341', max_length=64, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E Mail')),
                ('cuit', models.CharField(blank=True, max_length=16, null=True)),
                ('activo', models.NullBooleanField(default=True, verbose_name='Activo')),
                ('mr_fecha_ingreso', models.DateField(blank=True, null=True, verbose_name='Fecha Ingreso MR')),
                ('mr_legajo', models.IntegerField(blank=True, null=True, verbose_name='N de Legajo')),
                ('xlreparticion', models.CharField(blank=True, max_length=32, null=True, verbose_name='Reparticion')),
                ('xltipoemp', models.CharField(blank=True, max_length=32, null=True)),
                ('xlcaliflab', models.CharField(blank=True, max_length=32, null=True, verbose_name='Calificacion ')),
                ('xltitulo', models.CharField(blank=True, max_length=32, null=True)),
                ('mrmapid', models.IntegerField(blank=True, editable=False, null=True)),
                ('mrpersonaid', models.IntegerField(blank=True, editable=False, null=True)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateField(auto_now=True, null=True)),
                ('especialidad_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp1', to='entornos.Especialidad', verbose_name='Especialidad principal')),
                ('especialidad_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp2', to='entornos.Especialidad', verbose_name='Especialidad Dos')),
                ('especialidad_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp3', to='entornos.Especialidad', verbose_name='Especialidad Tres')),
                ('especialidad_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp4', to='entornos.Especialidad', verbose_name='Especialidad Cuatro')),
                ('mr_categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Categoria_lab', verbose_name='Categoria Municipal')),
                ('mr_statuslab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Status_lab', verbose_name='Condicion Laboral')),
                ('profesion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Profesion', verbose_name='Profesion')),
            ],
            options={
                'ordering': ['apellido'],
                'db_table': 'trabajadores',
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores Salud',
            },
        ),
        migrations.AddField(
            model_name='tarea_diferente',
            name='trb_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TrabajadorRedir', to='rechum.Trabajador', verbose_name='Trabajador Redefinido'),
        ),
        migrations.AddField(
            model_name='tarea_diferente',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='tarea_diferente',
            name='xdispodecidec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.DispoDesiDec', verbose_name='X Disposicion'),
        ),
        migrations.AddField(
            model_name='tarea_diferente',
            name='xjunta_medica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Junta_medica', verbose_name='X Junta medica'),
        ),
        migrations.AddField(
            model_name='tarea_diferente',
            name='xsolictrab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Solic_modif_trb', verbose_name='Solicitud de Trabajador'),
        ),
        migrations.AddField(
            model_name='solic_rhum',
            name='trb_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='Persona Sugerida'),
        ),
        migrations.AddField(
            model_name='solic_rhum',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='solic_rhum',
            name='xausenciatrab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Ausencia_trb', verbose_name='X Aus '),
        ),
        migrations.AddField(
            model_name='solic_modif_trb',
            name='trb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='Gestor promotor'),
        ),
        migrations.AddField(
            model_name='solic_modif_trb',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='registro_status',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechum.Status_lab', verbose_name='Estado Laboral registrado'),
        ),
        migrations.AddField(
            model_name='registro_status',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='registro_status',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='registro_especialidad',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='registro_especialidad',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='registro_categorias',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='Trabajador'),
        ),
        migrations.AddField(
            model_name='registro_categorias',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='junta_medica',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Resultado_junta', verbose_name='Resultado'),
        ),
        migrations.AddField(
            model_name='junta_medica',
            name='trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TraJuntap', to='rechum.Trabajador', verbose_name='Trabajador evaluado'),
        ),
        migrations.AddField(
            model_name='junta_medica',
            name='trb_evaluador_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evaluador_a', to='rechum.Trabajador', verbose_name='Evaluado Por'),
        ),
        migrations.AddField(
            model_name='junta_medica',
            name='trb_evaluador_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evaluador_b', to='rechum.Trabajador', verbose_name='Evaluado Por'),
        ),
        migrations.AddField(
            model_name='junta_medica',
            name='trb_evaluador_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evaluador_c', to='rechum.Trabajador', verbose_name='Evaluado Por'),
        ),
        migrations.AddField(
            model_name='junta_medica',
            name='trb_evaluador_d',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Evaluador_d', to='rechum.Trabajador', verbose_name='Evaluado Por'),
        ),
        migrations.AddField(
            model_name='dispodesidec',
            name='trb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='Gestor promotor'),
        ),
        migrations.AddField(
            model_name='dispodesidec',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='trb_prop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='Gestor promotor'),
        ),
        migrations.AddField(
            model_name='concurso',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='ausencia_trb',
            name='cobertura_princ_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TrCobertor', to='rechum.Trabajador', verbose_name='Cobertura Por'),
        ),
        migrations.AddField(
            model_name='ausencia_trb',
            name='diagnostico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Diagnostico', verbose_name='Diagnostico'),
        ),
        migrations.AddField(
            model_name='ausencia_trb',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Institucion '),
        ),
        migrations.AddField(
            model_name='ausencia_trb',
            name='tipo_ausencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Tipo_Ausencia_trb', verbose_name='Motivo de Solicitud'),
        ),
        migrations.AddField(
            model_name='ausencia_trb',
            name='trabajador_ausente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TrAreemp', to='rechum.Trabajador', verbose_name='Trabajador ausente'),
        ),
        migrations.AddField(
            model_name='ausencia_trb',
            name='usuario_registro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
