# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-16 23:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rechum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ausencia_trb',
            name='xtareasdif',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Tarea_diferente', verbose_name='TDifs'),
        ),
        migrations.AlterField(
            model_name='ausencia_trb',
            name='diagnostico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Diagnostico', verbose_name='Diagnostico'),
        ),
        migrations.AlterField(
            model_name='ausencia_trb',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Inicio Ausencia'),
        ),
        migrations.AlterField(
            model_name='ausencia_trb',
            name='tipo_ausencia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Tipo_Ausencia_trb', verbose_name='Motivo Ausencia'),
        ),
        migrations.AlterField(
            model_name='ausencia_trb',
            name='usuario_registro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AlterField(
            model_name='solic_rhum',
            name='institucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Institucion', verbose_name='Institucion Destino'),
        ),
        migrations.AlterField(
            model_name='solic_rhum',
            name='trb_sugerido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Trabajador', verbose_name='COBERTURA Sugerida'),
        ),
        migrations.AlterField(
            model_name='solic_rhum',
            name='xausenciatrab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rechum.Ausencia_trb', verbose_name='Solicit X Aus. '),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='especialidad_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Esp1', to='entornos.Especialidad', verbose_name='Especialidad'),
        ),
    ]
