# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-18 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_auto_20180518_1858'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rechum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_reemplazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgrevision', models.TextField(blank=True, null=True, verbose_name='Revision')),
                ('fecha_revision', models.DateTimeField(auto_now_add=True, null=True)),
                ('avaladoxsrvsalud', models.BooleanField(default=False, verbose_name='Aval SS')),
                ('reemplazo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicios.Reemplazo', verbose_name='MODULO DE REEMPLAZO')),
                ('usuario_registro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'db_table': 'reemplazo_avalado',
                'verbose_name': 'Reemplazo Revisado',
                'verbose_name_plural': ' Modificaciones de Estado ',
            },
        ),
    ]
