# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-19 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rechum', '0002_registro_reemplazo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registro_reemplazo',
            options={'verbose_name': 'Reemplazo Revisado', 'verbose_name_plural': 'Revision Reemplazos'},
        ),
    ]
