# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-22 22:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionalesUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodoc', models.CharField(max_length=5)),
                ('nrodoc', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'oytred_adicionales_usuarios',
            },
        ),
        migrations.CreateModel(
            name='AgrupadorEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.IntegerField()),
            ],
            options={
                'db_table': 'oytred_agrupadoresestudios',
            },
        ),
        migrations.CreateModel(
            name='AOclasif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=8)),
                ('comentarios', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'oytred_AO_clasificacion',
            },
        ),
        migrations.CreateModel(
            name='Camas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'oytred_camas',
            },
        ),
        migrations.CreateModel(
            name='Caso_pendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resuelto', models.BooleanField(default=False, verbose_name='RESUELTO')),
                ('fecha_trauma', models.DateField(blank=True, null=True, verbose_name='Fecha Trauma')),
                ('fecha_registro', models.DateField(verbose_name='Fecha Registro')),
                ('fecha_pre_quirurgico', models.DateField(blank=True, null=True, verbose_name='Fecha PRE Q')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateField(blank=True, null=True, verbose_name='Fecha Resolucion')),
                ('informe', models.TextField(default='Comentarios del Caso', verbose_name='Registro')),
                ('intediag', models.CharField(max_length=64, verbose_name='Clave busqueda')),
                ('img1', models.ImageField(blank=True, help_text='Busque archivo de imagen...', upload_to='cpds/%Y/%m')),
                ('img2', models.ImageField(blank=True, help_text='Busque archivo de imagen...', upload_to='cpds/%Y/%m')),
            ],
            options={
                'db_table': 'oytred_casos_pendientes',
            },
        ),
        migrations.CreateModel(
            name='Categorizacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('sigla', models.CharField(max_length=8)),
                ('detalle', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'oytred_categorias_profesionales',
            },
        ),
        migrations.CreateModel(
            name='Centrosalud',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('sigla', models.CharField(default='CS...', max_length=8)),
                ('refdtt', models.CharField(blank=True, max_length=6, verbose_name='Sigla efector DT')),
                ('referente', models.CharField(blank=True, max_length=64, null=True)),
                ('tipo', models.CharField(choices=[('PRV', 'provincial'), ('MNC', 'municipal'), ('NCN', 'nacional'), ('N/D', 'no determinado')], default='MNC', max_length=3)),
                ('telefono', models.CharField(blank=True, max_length=16)),
                ('domicilio', models.CharField(blank=True, max_length=128)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'oytred_centros_de_salud',
            },
        ),
        migrations.CreateModel(
            name='cie10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupodg', models.CharField(blank=True, choices=[('NC', 'no clasificado'), ('TRMT', 'traumatologico'), ('RSPT', 'respiratorio'), ('GSTN', 'gastrointestinal'), ('NFUR', 'nefrourologico'), ('SNCO', 'sistema nervioso'), ('CVSC', 'cardiovascular')], max_length=4, null=True)),
                ('categoria', models.CharField(blank=True, max_length=32, null=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=8)),
                ('comentarios', models.CharField(max_length=128)),
                ('habilitado', models.NullBooleanField(default=False)),
            ],
            options={
                'db_table': 'oytred_cie10',
            },
        ),
        migrations.CreateModel(
            name='Cirugia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quirofano', models.CharField(blank=True, max_length=4, null=True, verbose_name='QUIROFANO')),
                ('fecha_cirugia', models.DateField()),
                ('hora_ini_cirugia', models.TimeField(blank=True, null=True)),
                ('hora_fin_cirugia', models.TimeField(blank=True, null=True)),
                ('clavecirugia', models.CharField(default='cirugia', max_length=48, verbose_name='ClaveQ')),
                ('tipo', models.CharField(blank=True, choices=[('NDTM', 'no determinado'), ('QUR', 'CIRUGIA URGENCIA'), ('QPG', 'CIRUGIA PROGRAMADA')], max_length=4, null=True)),
                ('informe', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'oytred_cirugias',
            },
        ),
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=32)),
                ('localidad', models.CharField(default='PLACEHOLDER', max_length=128)),
                ('provincia', models.CharField(default='PLACEHOLDER', max_length=64)),
            ],
            options={
                'db_table': 'oytred_codigos_postales',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupodg', models.CharField(blank=True, choices=[('NC', 'no clasificado'), ('TRMT', 'traumatologico'), ('RSPT', 'respiratorio'), ('GSTN', 'gastrointestinal'), ('NFUR', 'nefrourodjango.contrib.contenttypeslogico'), ('SNCO', 'sistema nervioso'), ('CVSC', 'cardiovascular')], default='TRMT', max_length=4, null=True)),
                ('descripcion', models.CharField(max_length=64)),
                ('codigo', models.CharField(max_length=12)),
                ('comentarios', models.CharField(blank=True, max_length=128, null=True)),
                ('habilitado', models.NullBooleanField(default=False)),
                ('AOclasif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.AOclasif', verbose_name='AO clasificacion')),
                ('cie10', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.cie10', verbose_name='ref Cie 10')),
            ],
            options={
                'db_table': 'oytred_diagnosticos',
            },
        ),
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
                ('sigla', models.CharField(max_length=6)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'oytred_dietas',
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='distrito municipal ....', max_length=32)),
                ('sigla', models.CharField(default='DM', max_length=8)),
                ('responsable', models.CharField(default='j j d.....', max_length=64)),
                ('cmd', models.CharField(default='CMD ......', max_length=64)),
                ('comentarios', models.TextField(default='Registro detalles')),
            ],
            options={
                'db_table': 'oytred_distritos_municipales',
            },
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupoff', models.CharField(blank=True, choices=[('NC', 'no clasificado'), ('JFSL', 'jefe de sala'), ('LCNJ', 'supervisor'), ('EFSL', 'enfermero de sala'), ('EFTI', 'enfermero de criticos'), ('EFGD', 'enfermero de guardia'), ('EFQM', 'enfermero de quemados')], max_length=4, null=True, verbose_name='Grupo Enfermeria')),
                ('matricula', models.CharField(max_length=16)),
                ('apellido', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('domicilio', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'oytred_enfermeros',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'oytred_especialidades',
            },
        ),
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('texto', models.TextField()),
            ],
            options={
                'db_table': 'oytred_evoluciones',
            },
        ),
        migrations.CreateModel(
            name='EvolucionCardio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txtDSEF', models.TextField()),
                ('txtCET', models.TextField()),
                ('txtECG', models.TextField()),
                ('txtESF', models.TextField()),
                ('txtCI', models.TextField()),
                ('evolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Evolucion')),
            ],
            options={
                'db_table': 'oytred_evolCardio',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('href', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'oytred_formularios',
            },
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('sigla', models.CharField(max_length=9)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'oytred_grupos_profesionales',
            },
        ),
        migrations.CreateModel(
            name='Grupo_estad_implante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('sigla', models.CharField(max_length=8)),
                ('detalle', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'oytred_grupo_estadistico_implante',
            },
        ),
        migrations.CreateModel(
            name='GruposUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('estado', models.IntegerField()),
                ('pinicio', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'oytred_gruposUsuario',
            },
        ),
        migrations.CreateModel(
            name='GruposxUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.GruposUsuario')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oytred_gruposxusuarios',
            },
        ),
        migrations.CreateModel(
            name='Hallazgoguardia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sistema', models.CharField(max_length=2)),
                ('hallazgo', models.CharField(max_length=60)),
                ('color', models.CharField(max_length=10)),
                ('prioridad', models.IntegerField()),
                ('estado', models.IntegerField()),
            ],
            options={
                'db_table': 'oytred_hallazgosguardia',
            },
        ),
        migrations.CreateModel(
            name='Implante_comercial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=64)),
                ('marca', models.CharField(max_length=36)),
                ('modelo', models.CharField(blank=True, max_length=64, null=True)),
                ('detalles', models.TextField(blank=True, verbose_name='Caracteristicas del Implante')),
            ],
            options={
                'db_table': 'oytred_implantes_comerciales',
            },
        ),
        migrations.CreateModel(
            name='Implante_generico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=128)),
                ('detalles', models.TextField(blank=True, verbose_name='Caracteristicas del Implante')),
            ],
            options={
                'db_table': 'implantes_genericos',
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('sigla', models.CharField(max_length=8)),
                ('domicilio', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('comentarios', models.TextField(blank=True, default='N', null=True)),
                ('codigo_postal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.CodigoPostal')),
            ],
            options={
                'db_table': 'oytred_instituciones',
            },
        ),
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hclint', models.IntegerField(blank=True, null=True, verbose_name='Historia Clinica')),
                ('sala', models.CharField(default='NO DETERMINADA', max_length=64)),
                ('cama', models.CharField(max_length=4, null=True)),
                ('tipo', models.CharField(blank=True, choices=[('YNDT', 'no determinado'), ('YUR', 'INTERNACION URGENCIA'), ('YPG', 'INTERNACION PROGRAMADA')], max_length=4, null=True)),
                ('fecha_internacion', models.DateField(verbose_name='Ingreso')),
                ('fecha_egreso', models.DateField(blank=True, null=True, verbose_name='Alta')),
                ('intediag', models.CharField(blank=True, default='NR', max_length=64, null=True, verbose_name='ClaveMotivo')),
                ('germen', models.CharField(blank=True, max_length=36, null=True, verbose_name='Germen pr.')),
                ('lab', models.CharField(blank=True, max_length=36, null=True, verbose_name='laboratorio')),
                ('informe', models.TextField(blank=True)),
                ('img1', models.ImageField(blank=True, help_text='Archivo de imagen...', upload_to='internaciones/%Y/%m')),
                ('img2', models.ImageField(blank=True, help_text='Archivo de imagen', upload_to='internaciones/%Y/%m')),
                ('img3', models.ImageField(blank=True, help_text='Archivo de imagen', upload_to='internaciones/%Y/%m')),
                ('hora_internacion', models.TimeField(auto_now_add=True)),
                ('texto_epicrisis', models.TextField(blank=True, verbose_name='Texto Epicrisis')),
            ],
            options={
                'db_table': 'oytred_internaciones',
            },
        ),
        migrations.CreateModel(
            name='ItemLic_ofrecido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad ')),
                ('valor_unitario', models.IntegerField(verbose_name='Valor en pesos por unidad')),
                ('seleccionado', models.IntegerField()),
                ('comentarios', models.TextField(blank=True)),
                ('texto_asignacion', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'oytred_items_licitacion_ofrecidos',
            },
        ),
        migrations.CreateModel(
            name='ItemLic_solicitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad de elementos')),
                ('detalles', models.TextField(default='Con Asistencia Tecnica')),
                ('comentarios', models.TextField(blank=True)),
                ('precio_ref', models.TextField(blank=True)),
                ('adjudicado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.ItemLic_ofrecido')),
                ('grupoestad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Grupo_estad_implante')),
                ('implante_sol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Implante_generico', verbose_name='Item Solicitado')),
            ],
            options={
                'db_table': 'oytred_items_licitacion_solicitados',
            },
        ),
        migrations.CreateModel(
            name='ItemsEstudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=80)),
                ('tipo', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('agrupador', models.IntegerField()),
                ('auditado', models.IntegerField()),
                ('categoria', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'oytred_itemsestudios',
            },
        ),
        migrations.CreateModel(
            name='ItemStockUtilizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('largo', models.IntegerField()),
                ('diametro', models.IntegerField()),
                ('cirugia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Cirugia')),
                ('item_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.ItemLic_solicitado')),
            ],
            options={
                'db_table': 'oytred_items_stock_utilizados',
            },
        ),
        migrations.CreateModel(
            name='Licitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_licitacion', models.CharField(choices=[('RPURG', 'URGENTE REPOSICION'), ('PPURG', 'URGENTE P PACIENTE'), ('LPER', 'LICITACION PERIODICA'), ('N/C', 'NO CLASIFICADO')], default='PERIODICA', max_length=12, verbose_name='Tipo de Licitacion')),
                ('nombre', models.CharField(default='ddmmmyyyy', max_length=64, verbose_name='N licitacion')),
                ('fecha_carga', models.DateField()),
                ('fecha_solicitud', models.DateField(blank=True, db_column='fecha_solicitud', null=True, verbose_name='Fecha Solicitud')),
                ('fecha_apertura', models.DateField(blank=True, null=True, verbose_name='Fecha Apertura')),
                ('fecha_pre_adjudicacion', models.DateField(blank=True, null=True, verbose_name='Fecha Pre Adjudicacion')),
                ('detalles', models.TextField(verbose_name='Comentarios')),
                ('codred', models.CharField(max_length=20)),
                ('estado', models.IntegerField()),
                ('fecha_fdir', models.DateField()),
                ('fecha_fcont', models.DateField()),
                ('fecha_cierre', models.DateField()),
                ('hora_cierre', models.TimeField(blank=True, null=True)),
                ('fecha_cirugia', models.DateField()),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Diagnostico')),
                ('institucion', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion')),
                ('por_internacion', models.ForeignKey(blank=True, db_column='por_internacion', null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Internacion', verbose_name='Internacion')),
            ],
            options={
                'db_table': 'oytred_licitaciones',
            },
        ),
        migrations.CreateModel(
            name='Lista_de_espera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('fecha_creacion', models.DateField(verbose_name='Fecha Creacion')),
                ('comentarios', models.TextField(default='Registro', verbose_name='Comentarios')),
            ],
            options={
                'db_table': 'oytred_listas_de_espera',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('codigo', models.IntegerField()),
            ],
            options={
                'db_table': 'oytred_localidades',
            },
        ),
        migrations.CreateModel(
            name='LugarTrabajoProfesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion')),
            ],
            options={
                'db_table': 'lugarestrabajoprof',
            },
        ),
        migrations.CreateModel(
            name='LugarTrabajoUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oytred_lugarestrabajousu',
            },
        ),
        migrations.CreateModel(
            name='MarcaImplante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=128)),
                ('detalles', models.TextField(blank=True, verbose_name='')),
            ],
            options={
                'db_table': 'oytred_marcas_implantes',
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'oytred_modulos',
            },
        ),
        migrations.CreateModel(
            name='MultimediaInternacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('texto', models.TextField()),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Internacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'oytred_multimediaxint',
            },
        ),
        migrations.CreateModel(
            name='Nacionalidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'oytred_nacionalidades',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('tipo_documento', models.CharField(choices=[('DU', 'documento unico'), ('ND', 'no determinado'), ('LE', 'libreta de enrolamiento'), ('LC', 'libreta c\xedvica'), ('PA', 'pasaporte'), ('CE', 'c\xe9dula federal'), ('CM', 'certificado migratorio'), ('ET', 'en tr\xe1mite')], default='DU', max_length=2)),
                ('numero_documento', models.IntegerField(blank=True, default=0, null=True, verbose_name='N de Doc ')),
                ('doc_cons', models.BooleanField(default=False, verbose_name='Doc Consolidado')),
                ('dtpacid', models.CharField(blank=True, max_length=36, null=True, verbose_name='NDTech')),
                ('fecha_nacimiento', models.DateField()),
                ('estado_civil', models.CharField(blank=True, choices=[('ND', 'no determinado'), ('SO', 'soltero'), ('CA', 'casado'), ('VI', 'viudo'), ('SL', 'separado legal'), ('SH', 'separado de hecho'), ('DI', 'divorciado'), ('CO', 'conviviente')], max_length=2, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('M', 'masculino'), ('F', 'femenino'), ('I', 'no determinado')], max_length=1, null=True)),
                ('nacionalidad', models.CharField(choices=[('ND', 'No definido'), ('AFG', 'Afganist\xe1n'), ('ALA', '\xc5land'), ('ALB', 'Albania'), ('DEU', 'Alemania'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('AIA', 'Anguila'), ('ATA', 'Ant\xe1rtida'), ('ATG', 'Antigua y Barbuda'), ('ANT', 'Antillas Neerlandesas'), ('SAU', 'Arabia Saudita'), ('DZA', 'Argelia'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ABW', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaiy\xe1n'), ('BHS', 'Bahamas'), ('BHR', 'Bahr\xe9in'), ('BGD', 'Bangladesh'), ('BRB', 'Barbados'), ('BEL', 'B\xe9lgica'), ('BLZ', 'Belice'), ('BEN', 'Ben\xedn'), ('BMU', 'Bermudas'), ('BLR', 'Bielorrusia'), ('MMR', 'Birmania'), ('BOL', 'Bolivia'), ('BIH', 'Bosnia y Herzegovina'), ('BWA', 'Botsuana'), ('BVT', 'Noruega Isla Bouvet'), ('BRA', 'Brasil'), ('BRN', 'Brun\xe9i'), ('BGR', 'Bulgaria'), ('BFA', 'Burkina Faso'), ('BDI', 'Burundi'), ('BTN', 'But\xe1n'), ('CPV', 'Cabo Verde'), ('CYM', 'Islas Caim\xe1n'), ('KHM', 'Camboya'), ('CMR', 'Camer\xfan'), ('CAN', 'Canad\xe1'), ('CAF', 'Rep\xfablica Centroafricana'), ('TCD', 'Chad'), ('CZE', 'Rep\xfablica Checa'), ('CHL', 'Chile'), ('CHN', 'China'), ('CYP', 'Chipre'), ('CCK', 'Islas Cocos'), ('COL', 'Colombia'), ('COM', 'Comoras'), ('COG', 'Rep\xfablica del Congo'), ('COD', 'Rep\xfablica Democr\xe1tica del Congo'), ('COK', 'Islas Cook'), ('PRK', 'Corea del Norte'), ('KOR', 'Corea del Sur'), ('CIV', 'Costa de Marfil'), ('CRI', 'Costa Rica'), ('HRV', 'Croacia'), ('CUB', 'Cuba'), ('DNK', 'Dinamarca'), ('DMA', 'Dominica'), ('DOM', 'Rep\xfablica Dominicana'), ('ECU', 'Ecuador'), ('EGY', 'Egipto'), ('SLV', 'El Salvador'), ('ARE', 'Emiratos \xc1rabes Uniclass Pacdos'), ('ERI', 'Eritrea'), ('SVK', 'Eslovaquia'), ('SVN', 'Eslovenia'), ('ESP', 'Espa\xf1a'), ('USA', 'Estados Unidos'), ('UMI', 'Islas ultramarinas de Estados Unidos'), ('EST', 'Estonia'), ('ETH', 'Etiop\xeda'), ('FRO', 'Islas Feroe'), ('PHL', 'Filipinas'), ('FIN', 'Finlandia'), ('FJI', 'Fiyi'), ('FRA', 'Francia'), ('GAB', 'Gab\xf3n'), ('GMB', 'Gambia'), ('GEO', 'Georgia'), ('SGS', 'Islas Georgias del Sur y Sandwich del Sur'), ('GHA', 'Ghana'), ('GIB', 'Gibraltar'), ('GRD', 'Granada'), ('GRC', 'Grecia'), ('GRL', 'Groenlandia'), ('GLP', 'Guadalupe'), ('GUM', 'Guam'), ('GTM', 'Guatemala'), ('GUF', 'Guayana Francesa'), ('GGY', 'Guernsey'), ('GIN', 'Guinea'), ('GNQ', 'Guinea Ecuatorial'), ('GNB', 'Guinea-Bissau'), ('GUY', 'Guyana'), ('HTI', 'Hait\xed'), ('HMD', 'Australia Islas Heard y McDonald'), ('HND', 'Honduras'), ('HKG', 'Hong Kong'), ('HUN', 'Hungr\xeda'), ('IND', 'India'), ('IDN', 'Indonesia'), ('IRN', 'Ir\xe1n'), ('IRQ', 'Iraq'), ('IRL', 'Irlanda'), ('ISL', 'Islandia'), ('ISR', 'Israel'), ('ITA', 'Italia'), ('JAM', 'Jamaica'), ('JPN', 'Jap\xf3n'), ('JEY', 'Jersey'), ('JOR', 'Jordania'), ('KAZ', 'Kazajist\xe1n'), ('KEN', 'Kenia'), ('KGZ', 'Kirguist\xe1n'), ('KIR', 'Kiribati'), ('KWT', 'Kuwait'), ('LAO', 'Laos'), ('LSO', 'Lesoto'), ('LVA', 'Letonia'), ('LBN', 'L\xedbano'), ('LBR', 'Liberia'), ('LBY', 'Libia'), ('LIE', 'Liechtenstein'), ('LTU', 'Lituania'), ('LUX', 'Luxemburgo'), ('MAC', 'Macao'), ('MKD', 'Rep\xfablica de Macedonia'), ('MDG', 'Madagascar'), ('MYS', 'Malasia Malasia'), ('MWI', 'Malaui'), ('MDV', 'Maldivas'), ('MLI', 'Mal\xed'), ('MLT', 'Malta'), ('FLK', 'Islas Malvinas'), ('IMN', 'Isla de Man'), ('MNP', 'Islas Marianas del Norte'), ('MAR', 'Marruecos Marruecos'), ('MHL', 'Islas Marshall'), ('MTQ', 'Martinica'), ('MUS', 'Mauricio'), ('MRT', 'Mauritania'), ('MYT', 'Mayotte'), ('MEX', 'M\xe9xico M\xe9xico'), ('FSM', 'Micronesia'), ('MDA', 'Moldavia'), ('MCO', 'M\xf3naco'), ('MNG', 'Mongolia'), ('MNE', 'Montenegro'), ('MSR', 'Montserrat'), ('MOZ', 'Mozambique'), ('NAM', 'Namibia'), ('NRU', 'Nauru'), ('CXR', 'Isla de Navidad'), ('NPL', 'Nepal Nepal'), ('NIC', 'Nicaragua'), ('NER', 'N\xedger'), ('NGA', 'Nigeria'), ('NIU', 'Niue'), ('NFK', 'Norfolk'), ('NOR', 'Noruega'), ('NCL', 'Nueva Caledonia'), ('NZL', 'Nueva Zeclass PracticaQlanda'), ('OMN', 'Om\xe1n'), ('NLD', 'Pa\xedses Bajos'), ('PAK', 'Pakist\xe1n'), ('PLW', 'Palaos'), ('PSE', 'Territorios palestinos'), ('PAN', 'Panam\xe1'), ('PNG', 'Pap\xfaa Nueva Guinea'), ('PRY', 'Paraguay'), ('PER', 'Per\xfa'), ('PCN', 'Islas Pitcairn'), ('PYF', 'Polinesia Francesa'), ('POL', 'Polonia'), ('PRT', 'Portugal'), ('PRI', 'Puerto Rico'), ('QAT', 'Qatar'), ('GBR', 'Reino Unido'), ('REU', 'Reuni\xf3n'), ('RWA', 'Ruanda'), ('ROU', 'Rumania'), ('RUS', 'Rusia'), ('ESH', 'Rep\xfablica \xc1rabe Saharaui Democr\xe1tica'), ('SLB', 'Islas Salom\xf3n'), ('WSM', 'Samoa'), ('ASM', 'Samoa Americana'), ('BLM', 'San Bartolom\xe9'), ('KNA', 'San Crist\xf3bal y Nieves'), ('SMR', 'San Marino'), ('MAF', 'Saint-Martin'), ('SPM', 'San Pedro y Miquel\xf3n'), ('VCT', 'San Vicente y las Granadinas'), ('AFG', 'Afganist\xe1n'), ('ALA', '\xc5land'), ('ALB', 'Albania'), ('DEU', 'Alemania'), ('AND', 'Andorra'), ('AGO', 'Angola'), ('AIA', 'Anguila'), ('ATA', 'Ant\xe1rtida'), ('ATG', 'Antigua y Barbuda'), ('ANT', 'Antillas Neerlandesas'), ('SAU', 'Arabia Saudita'), ('DZA', 'Argelia'), ('ARG', 'Argentina'), ('ARM', 'Armenia'), ('ABW', 'Aruba'), ('AUS', 'Australia'), ('AUT', 'Austria'), ('AZE', 'Azerbaiy\xe1n'), ('SHN', 'Santa Helena'), ('LCA', 'Santa Luc\xeda'), ('STP', 'Santo Tom\xe9 y Pr\xedncipe'), ('SEN', 'Senegal'), ('SRB', 'Serbia'), ('SYC', 'Seychelles'), ('SLE', 'Sierra Leona'), ('SGP', 'Singapur'), ('SYR', 'Siria'), ('SOM', 'Somalia'), ('LKA', 'Sri Lanka'), ('SWZ', 'Suazilandia'), ('ZAF', 'Sud\xe1frica'), ('SDN', 'Sud\xe1n'), ('SWE', 'Suecia'), ('CHE', 'Suiza'), ('SUR', 'Surinam'), ('SJM', 'Svalbard y Jan Mayen'), ('THA', 'Tailandia'), ('TWN', 'Taiw\xe1n'), ('TZA', 'Tanzania'), ('TJK', 'Tayikist\xe1n'), ('IOT', 'Territorio Brit\xe1nico del Oc\xe9ano \xcdndico'), ('ATF', 'Territorios Australes Franceses'), ('TLS', 'Timor Oriental'), ('TGO', 'Togo'), ('TKL', 'Tokelau'), ('TON', 'Tonga'), ('TTO', 'Trinidad y Tobago'), ('TUN', 'T\xfanez T\xfanez'), ('TCA', 'Islas Turcas y Caicos'), ('TKM', 'Turkmenist\xe1n'), ('TUR', 'Turqu\xeda'), ('TUV', 'Tuvalu'), ('UKR', 'Ucrania'), ('UGA', 'Uganda'), ('URY', 'Uruguay'), ('UZB', 'Uzbekist\xe1n'), ('VUT', 'Vanuatu'), ('VAT', 'Ciudad del Vaticano'), ('VEN', 'Venezuela'), ('VNM', 'Vietnam'), ('VGB', 'Islas V\xedrgenes Brit\xe1nicas'), ('VIR', 'Islas V\xedrgenes Estadounidenses'), ('WLF', 'Wallis y Futuna'), ('YEM', 'Yemen'), ('DJI', 'Yibuti'), ('ZMB', 'Zambia'), ('ZWE', 'Zimbabue')], default='ARG', max_length=36)),
                ('provincia', models.CharField(choices=[('01', 'CAPITAL FEDERAL'), ('02', 'BUENOS AIRES'), ('03', 'CATAMARCA'), ('04', 'CORDOBA'), ('05', 'CORRIENTES'), ('06', 'ENTRE RIOS'), ('07', 'JUJUY'), ('08', 'LA RIOJA'), ('09', 'MENDOZA'), ('10', 'SALTA'), ('11', 'SAN JUAN'), ('12', 'SAN LUIS'), ('13', 'SANTA FE'), ('14', 'SANTIAGO DEL ESTERO'), ('15', 'TUCUMAN'), ('16', 'CHACO'), ('17', 'CHUBUT'), ('18', 'FORMOSA'), ('19', 'LA PAMPA'), ('20', 'MISIONES'), ('21', 'NEUQUEN'), ('22', 'RIO NEGRO'), ('23', 'SANTA CRUZ'), ('24', 'TIERRA DEL FUEGO')], default='13', max_length=2)),
                ('domicilio', models.CharField(blank=True, max_length=128)),
                ('telefono', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('domicilio_trabajo', models.CharField(blank=True, default='No Registrado', max_length=128)),
                ('comentarios', models.TextField(blank=True, default='No comentarios', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('dtlocalidad', models.CharField(blank=True, max_length=64, null=True, verbose_name='DTloc')),
                ('csr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Centrosalud', verbose_name='Centro de Salud')),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Localidad')),
            ],
            options={
                'db_table': 'oytred_pacientes',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Formulario')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Grupo')),
            ],
            options={
                'db_table': 'oytred_perfiles',
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'oytred_permisos',
            },
        ),
        migrations.CreateModel(
            name='PracticaQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupopq', models.CharField(blank=True, choices=[('NC', 'no clasificado'), ('RDS', 'reducciones simples'), ('RDF', 'reducciones y fijacion con clavijas'), ('ATA', 'artroplastias'), ('NTVRF', 'rafias'), ('OSDF', 'osteosintesis diafisarias'), ('MIPO', 'osteosintesis con placas mini invasivas'), ('OSPA', 'osteosintesis paraarticulares'), ('XTIM', 'extraccion implantes'), ('NCNM', 'enclavijados endomedulares'), ('TTHS', 'toiletes heridas'), ('TTFE', 'toiletes fx expuestas')], max_length=6, null=True)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'oytred_practicas',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(blank=True, max_length=16, null=True)),
                ('apellido', models.CharField(max_length=128)),
                ('nombre', models.CharField(max_length=128)),
                ('tipodoc', models.CharField(max_length=5)),
                ('nrodoc', models.IntegerField()),
                ('delared', models.BooleanField(default=True, verbose_name='Revista en la Red')),
                ('cargahs', models.IntegerField(blank=True, null=True, verbose_name='Horas Semanales en Inst Ref')),
                ('domicilio', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cuit', models.CharField(blank=True, max_length=16, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('tipo', models.CharField(blank=True, max_length=2)),
                ('dtid', models.IntegerField(blank=True, editable=False, null=True)),
                ('comentarios', models.TextField(blank=True, null=True, verbose_name='Comentarios')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Categorizacion', verbose_name='Categoria Profesional')),
                ('csr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Centrosalud')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Especialidad')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Grupo', verbose_name='Grupo Prof')),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion', verbose_name='Referencia Institucional')),
                ('nacionalidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Nacionalidad')),
            ],
            options={
                'db_table': 'oytred_profesionales',
            },
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=16)),
                ('nombre', models.CharField(max_length=128)),
                ('referente', models.CharField(max_length=128)),
                ('detalles', models.TextField()),
                ('domicilio', models.CharField(blank=True, max_length=128, null=True)),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(blank=True, max_length=16)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('cuit', models.CharField(blank=True, max_length=18, null=True)),
            ],
            options={
                'db_table': 'oytred_provedores',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('orden', models.IntegerField()),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion')),
            ],
            options={
                'db_table': 'oytred_salas',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('codigo', models.CharField(max_length=8)),
                ('descripcion', models.TextField()),
            ],
            options={
                'db_table': 'oytred_servicios',
            },
        ),
        migrations.CreateModel(
            name='ServiciosInstitucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Servicio')),
            ],
            options={
                'db_table': 'oytred_serviciosxinstituciones',
            },
        ),
        migrations.CreateModel(
            name='StockTraumato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('item_ofrecido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.ItemLic_ofrecido')),
                ('item_solicitado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.ItemLic_solicitado')),
                ('licitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Licitacion')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Implante_generico')),
            ],
            options={
                'db_table': 'oytred_stocktraumato',
            },
        ),
        migrations.CreateModel(
            name='Tipo_implante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('sigla', models.CharField(max_length=8)),
                ('detalle', models.TextField(blank=True)),
                ('padre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Tipo_implante')),
            ],
            options={
                'db_table': 'oytred_tipos_implante',
            },
        ),
        migrations.AddField(
            model_name='perfil',
            name='permiso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Permiso'),
        ),
        migrations.AddField(
            model_name='lugartrabajoprofesional',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Profesional'),
        ),
        migrations.AddField(
            model_name='lugartrabajoprofesional',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Servicio'),
        ),
        migrations.AddField(
            model_name='lista_de_espera',
            name='pacargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lep', to='oytred.Profesional', verbose_name='A Cargo'),
        ),
        migrations.AddField(
            model_name='lista_de_espera',
            name='payudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lepay', to='oytred.Profesional', verbose_name='Residente'),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='por_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Paciente'),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='prof_sol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Profesional'),
        ),
        migrations.AddField(
            model_name='licitacion',
            name='servicio',
            field=models.ForeignKey(blank=True, db_column='servicio', null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='itemstockutilizado',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Licitacion'),
        ),
        migrations.AddField(
            model_name='itemlic_solicitado',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Licitacion'),
        ),
        migrations.AddField(
            model_name='itemlic_ofrecido',
            name='implante_sol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.ItemLic_solicitado', verbose_name='Item Solicitado'),
        ),
        migrations.AddField(
            model_name='itemlic_ofrecido',
            name='licitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Licitacion'),
        ),
        migrations.AddField(
            model_name='itemlic_ofrecido',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.MarcaImplante'),
        ),
        migrations.AddField(
            model_name='itemlic_ofrecido',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Provedor'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='clinico_a_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ClinicoAcargo', to='oytred.Profesional', verbose_name='Clinico A Cargo'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='diagnostico_cuarto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='YdiagnosticoC', to='oytred.Diagnostico', verbose_name='Diagnostico Cuart'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='diagnostico_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='YdiagnosticoP', to='oytred.Diagnostico', verbose_name='Diagnostico principal'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='diagnostico_secundario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='YdiagnosticoB', to='oytred.Diagnostico', verbose_name='Diagnostico secundario'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='diagnostico_terciario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='YdiagnosticoT', to='oytred.Diagnostico', verbose_name='Diagnostico Terc'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='dieta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Dieta'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='enfermero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Enfermero'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Grupo', verbose_name='Grupo a Cargo'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Paciente'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='profayudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Iresi', to='oytred.Profesional', verbose_name='Profesional Junior(MF)'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='profesional_acargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IprofA', to='oytred.Profesional', verbose_name='Prof a cargo'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='profesional_intgdia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='IprofG', to='oytred.Profesional', verbose_name='J Guardia'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='profregint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pint', to='oytred.Profesional', verbose_name='Internado por'),
        ),
        migrations.AddField(
            model_name='internacion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Servicio', verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='implante_generico',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Tipo_implante'),
        ),
        migrations.AddField(
            model_name='implante_comercial',
            name='generico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Implante_generico', verbose_name='Generico'),
        ),
        migrations.AddField(
            model_name='implante_comercial',
            name='provedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Provedor'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='hospital',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion', verbose_name='Hospital/INstitucion'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Servicio'),
        ),
        migrations.AddField(
            model_name='formulario',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Modulo'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='internacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Internacion'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='profesional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Profesional'),
        ),
        migrations.AddField(
            model_name='evolucion',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Servicio'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='anestesista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anestesista', to='oytred.Profesional'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='cirujano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pcirujano', to='oytred.Profesional', verbose_name='Cirujano'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='diagnostico_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticoB', to='oytred.Diagnostico'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='diagnostico_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticoC', to='oytred.Diagnostico'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='diagnostico_D',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticoD', to='oytred.Diagnostico'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='diagnostico_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticoP', to='oytred.Diagnostico'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='oytred.Institucion', verbose_name='Institucion'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='implante_a',
            field=models.ForeignKey(blank=True, db_column='implante_a', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ItsA', to='oytred.ItemLic_solicitado', verbose_name='ITLICA'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='internacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Internacion'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Paciente', verbose_name='Paciente'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='payudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ayudante', to='oytred.Profesional', verbose_name='Ayudante 1'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='practica_B',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaB', to='oytred.PracticaQ'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='practica_C',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaC', to='oytred.PracticaQ'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='practica_D',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaD', to='oytred.PracticaQ'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='practica_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practicaP', to='oytred.PracticaQ'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='sayudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sayudante', to='oytred.Profesional', verbose_name='Ayudante2'),
        ),
        migrations.AddField(
            model_name='cirugia',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Servicio', verbose_name='ServicioQ'),
        ),
        migrations.AddField(
            model_name='centrosalud',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Distrito'),
        ),
        migrations.AddField(
            model_name='caso_pendiente',
            name='diagnos_a',
            field=models.ForeignKey(blank=True, db_column='diagnos_a', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gdiagnosticoP', to='oytred.Diagnostico', verbose_name='Diagnostico principal'),
        ),
        migrations.AddField(
            model_name='caso_pendiente',
            name='internacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Internacion'),
        ),
        migrations.AddField(
            model_name='caso_pendiente',
            name='listado_espera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Lista_de_espera'),
        ),
        migrations.AddField(
            model_name='caso_pendiente',
            name='pacargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cppp', to='oytred.Profesional', verbose_name='ProfResp'),
        ),
        migrations.AddField(
            model_name='caso_pendiente',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Paciente'),
        ),
        migrations.AddField(
            model_name='caso_pendiente',
            name='payudante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cppa', to='oytred.Profesional', verbose_name='Residente'),
        ),
        migrations.AddField(
            model_name='caso_pendiente',
            name='qcgresol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='oytred.Cirugia', verbose_name='Cirugia Resolvente'),
        ),
        migrations.AddField(
            model_name='camas',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Sala'),
        ),
        migrations.AddField(
            model_name='adicionalesusuario',
            name='gprincipal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.GruposUsuario'),
        ),
        migrations.AddField(
            model_name='adicionalesusuario',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Nacionalidad'),
        ),
        migrations.AddField(
            model_name='adicionalesusuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
