# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-05-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('entornos', '0003_obrasocial'),
        ('oytred', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('comentarios', models.TextField(default='Hallazgos', verbose_name='Comentarios y Hallazgos')),
                ('internacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Internacion')),
                ('obscl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entornos.Obrasocial', verbose_name='Obra Social')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Paciente')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oytred.Profesional')),
            ],
            options={
                'db_table': 'aconsultorio_consultas',
            },
        ),
        migrations.RemoveField(
            model_name='evolucion',
            name='institucion',
        ),
        migrations.RemoveField(
            model_name='evolucion',
            name='internacion',
        ),
        migrations.RemoveField(
            model_name='evolucion',
            name='servicio',
        ),
        migrations.AddField(
            model_name='evolucion',
            name='content_type',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='evolucion',
            table='evoluciones',
        ),
    ]
